// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://njtqxafpghereooloynv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5qdHF4YWZwZ2hlcmVvb2xveW52Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxMTYwMDQsImV4cCI6MjA1NzY5MjAwNH0.LvOYFok6vb8AFwM7BykxcXTu80MG35s4AFpD8HTE8lA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);